--- #YAML:1.0
name: Acme-Mobile-Thurblings
version: 0.01
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: count keystrokes to write mobile text messages
license: perl
requires:
  Carp: 0
  YAML: 0.35
  perl: 5.6.1
build_requires:
  Test::More: 0
provides:
  Acme::Mobile::Thurblings:
    file: lib/Acme/Mobile/Thurblings.pm
    version: 0.01
generated_by: Module::Build version 0.2607
